language: ruby
install: "bundle install"
script: "bundle exec rspec"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
gemfile:
  - gemfiles/activerecord-3.0.gemfile
  - gemfiles/activerecord-3.1.gemfile
  - gemfiles/activerecord-3.2.gemfile
  - gemfiles/activerecord-4.0.gemfile
  - gemfiles/activerecord-4.1.gemfile
  - gemfiles/datamapper-1.0.gemfile
  - gemfiles/datamapper-1.1.gemfile
  - gemfiles/datamapper-1.2.gemfile
  - gemfiles/mongomapper-0.10.gemfile
  - gemfiles/mongomapper-0.11.gemfile
  - gemfiles/mongomapper-0.12.gemfile
  - gemfiles/mongomapper-0.13.gemfile
